#!/usr/bin/env bash

inotifywait -m -e moved_to -e create --format "%f" ~/Downloads | while

for file in ~/Downloads/*.txt; do
    if [[ -f "$file" ]]; then
        mv $file ~/Downloads/text
    fi  
done

for file in ~/Downloads/*.pdf; do
    if [[ -f "$file" ]]; then
        mv $file /home/linton/Downloads/pdfs
    fi
done
     

for file in ~/Downloads/*.docx; do
    if [[ -f "$file" ]]; then
        mv $file /home/linton/Downloads/docs
    fi  
done  
     

for file in ~/Downloads/*.png; do
    if [[ -f "$file" ]]; then
        mv $file /home/linton/Downloads/images
    fi  
done



for file in ~/Downloads/*.jpg; do
    if [[ -f "$file" ]]; then
        mv $file /home/linton/Downloads/images
    fi  
done

for file in ~/Downloads/*; do
    if [[ -f "$file" ]]; then
        mv $file /home/linton/Downloads/other
    fi  

done

