#!/usr/bin/env bash

mkdir -p ~/Downloads/text
mkdir -p ~/Downloads/pdfs
mkdir -p ~/Downloads/docs
mkdir -p ~/Downloads/images
mkdir -p ~/Downloads/zip
mkdir -p ~/Downloads/excel
mkdir -p ~/Downloads/other

inotifywait -m -e moved_to -e create --format "$f" ~/Downloads | while read file
do

for file in ~/Downloads/*.txt; do
    if [[ -f "$file" ]]; then
        mkdir -p ~/Downloads/text
        mv $file ~/Downloads/text
    fi
done


for file in ~/Downloads/*.pdf; do
    if [[ -f "$file" ]]; then
        mkdir -p ~/Downloads/pdfs
        mv $file ~/Downloads/pdfs
    fi
done 


for file in ~/Downloads/*.docx; do
    if [[ -f "$file" ]]; then
        mkdir -p ~/Downloads/docs
        mv $file ~/Downloads/docs
    fi  
done
     

for file in ~/Downloads/*.png; do
    if [[ -f "$file" ]]; then
        mkdir -p ~/Downloads/images
        mv $file ~/Downloads/images
    fi  
done


for file in ~/Downloads/*.jpg; do
    if [[ -f "$file" ]]; then
        mkdir -p ~/Downloads/images
        mv $file ~/Downloads/images
    fi  
done


for file in ~/Downloads/*.zip; do
    if [[ -f "$file" ]]; then
        mkdir -p ~/Downloads/zip
        mv $file ~/Downloads/zip
    fi  
done


for file in ~/Downloads/*.xlsx; do
    if [[ -f "$file" ]]; then
        mkdir -p ~/Downloads/excel
        mv $file ~/Downloads/excel
    fi  
done


for file in ~/Downloads/*; do
    if [[ -f "$file" ]]; then
        mkdir -p ~/Downloads/other
        mv $file ~/Downloads/other
    fi  
done

done





