#!/usr/bin/env bash

for file in ~/Downloads/*.txt; do
    if [[ -f "$file" ]]; then
        mv $file /home/linton/Downloads/text
    fi  
done



for file in ~/Downloads/*.pdf; do
    if [[ -f "$file" ]]; then
        mv $file /home/linton/Downloads/pdfs
    fi
done
     

for file in ~/Downloads/*.docx; do
    if [[ -f "$file" ]]; then
        mv $file /home/linton/Downloads/docs
    fi  
done



     

